#!/bin/bash

TMPFILE=/tmp/cchttpd.tmp

var=$a
var2=$b

result=$(( $var + $var2  ))
echo '<html>
	<head>
		<title>RESULT</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	</head>
	<body>' > $TMPFILE
echo "<br/><h1>计算结果</h1><br/>" >> $TMPFILE
echo "这是计算结果页面，这个页面是由<br/>" >> $TMPFILE
echo "/www/show生成的，show通过环境变<br/>" >> $TMPFILE
echo "量获取两个数字，然后将他们做加法，<br/>" >> $TMPFILE
echo "用结果生成这个页面<br/><br/>" >> $TMPFILE
echo "<h2>" >> $TMPFILE
echo "$var + $var2 = $result" >> $TMPFILE
echo "</h2>" >> $TMPFILE
echo "<a href=\"post.html\">try again</a>" >> $TMPFILE
echo "</body></html>" >> $TMPFILE
len=`ls -l $TMPFILE | awk '{print $5}'`


printf "HTTP/1.1 200 OK\r\n" 
printf "Content-Type: text/html\r\n" 
printf "Connection: Keep-Alive\r\n" 
printf "Content-Length: %d\r\n" $len 
printf "\r\n"
cat $TMPFILE 
exit 0
